#:import Window kivy.core.window.Window
<PlantView>:
    orientation : 'vertical'
    canvas.before:
        Color:
            rgba: app.colors.primary
        Rectangle:
            pos:self.pos
            size:self.size

    RelativeLayout:
        BoxLayout:
            orientation : 'vertical'
            AnchorLayout:
                orientation : 'vertical'
                size_hint_y: None
                height: dp(18)
                anchor_x: 'left'
                BoxLayout:
                    padding :dp(4)
                    size_hint:[None,None]
                    size:[dp(24),dp(24)]
                    IconButton:
                        source :'assets/icons/ic_back.png'
                        on_release:app.root.ids.scrn_mngr.current = 'scrn_home'
            BoxLayout:
                orientation : 'vertical'
                size_hint_y: 0.4
                padding:[dp(14),dp(8)]
                Text:
                    text : root.station
                    font_size : app.fonts.size.h6
                    color:app.colors.secondary
                    font_name:app.fonts.body
                    size_hint_y :None
                    height : dp(12)
                    valign : 'bottom'
                Text:
                    text : root.name
                    font_size : app.fonts.size.h1
                    color:app.colors.white
                    font_name:app.fonts.heading
                    size_hint_y :None
                    height : dp(42)

                AnchorLayout:
                    anchor_x: 'left'
                    size_hint_y: None
                    height : dp(54)
                    BoxLayout:
                        size_hint: [0.35, None]
                        height: dp(32)
                        padding:[dp(4), dp(2)]
                        canvas.before:
                            Color:
                                rgba:[1,1,1,0.1]
                            RoundedRectangle:
                                pos:self.pos
                                size:self.size
                                radius: [self.height/2]
                        BoxLayout:
                            size_hint_x: None
                            width: self.height
                            padding: dp(4)
                            IconButton:
                                source:'assets/icons/ic_image.png'

                        Text:
                            text : 'Add Photo'
                            font_size : app.fonts.size.h6
                            color:app.colors.white
                            font_name:app.fonts.body

                BoxLayout:
                    size_hint_x:0.65
                    padding:[dp(0), dp(8)]
                    spacing : dp(8)
                    BoxLayout:
                        orientation: 'vertical'
                        padding:dp(12)
                        spacing : dp(8)
                        canvas.before:
                            Color:
                                rgba: [1,1,1,0.1]
                            RoundedRectangle:
                                pos:self.pos
                                size:self.size
                                radius:[self.height*0.2]
                        AnchorLayout:
                            BoxLayout:
                                size_hint:[None, 1]
                                width :self.height
                                canvas.before:
                                    Color:
                                        rgba: app.colors.primary
                                    Ellipse:
                                        pos:self.pos
                                        size:self.size

                                Image:
                                    source:'assets/icons/ic_can.png'
                        BoxLayout:
                            orientation: 'vertical'
                            Text:
                                text : 'Lambda'
                                font_size : app.fonts.size.h6
                                color:app.colors.white
                                font_name:app.fonts.subheading
                                halign:'center'
                            Text:
                                text : '4 age'
                                font_size : app.fonts.size.h6
                                color:app.colors.secondary
                                font_name:app.fonts.body
                                halign:'center'

                    BoxLayout:
                        orientation: 'vertical'
                        padding:dp(12)
                        spacing : dp(8)
                        canvas.before:
                            Color:
                                rgba: [1,1,1,0.1]
                            RoundedRectangle:
                                pos:self.pos
                                size:self.size
                                radius:[self.height*0.2]
                        AnchorLayout:
                            BoxLayout:
                                size_hint:[None, 1]
                                width :self.height
                                canvas.before:
                                    Color:
                                        rgba: app.colors.primary
                                    Ellipse:
                                        pos:self.pos
                                        size:self.size

                                Image:
                                    source:'assets/icons/ic_plant.png'
                        BoxLayout:
                            orientation: 'vertical'
                            Text:
                                text : 'Cow'
                                font_size : app.fonts.size.h6
                                color:app.colors.white
                                font_name:app.fonts.subheading
                                halign:'center'
                            Text:
                                text : '5 age'
                                font_size : app.fonts.size.h6
                                color:app.colors.secondary
                                font_name:app.fonts.body
                                halign:'center'



            BoxLayout:
                orientation : 'vertical'
                size_hint_y: 0.6
                padding:dp(14)
                spacing: dp(8)
                canvas.before:
                    Color:
                        rgba: app.colors.white
                    RoundedRectangle:
                        pos:self.pos
                        size:self.size
                        radius:[dp(23),dp(23),0,0]

                BoxLayout:
                    size_hint_y: None
                    height:dp(42)
                    spacing: dp(8)
                    size_hint_x: 0.6
                    SmoothToggle:
                        text: 'About'
                        state:'down'
                    SmoothToggle:
                        text: 'Tips'
                    SmoothToggle:
                        text: 'Activity'
                Text:
                    text : 'Carrefour'
                    font_size : app.fonts.size.h1
                    color:app.colors.primary
                    font_name:app.fonts.heading
                    size_hint_y :None
                    height:dp(42)
                Text:
                    text : 'Butchery'
                    font_size : app.fonts.size.h4
                    color:app.colors.primary
                    font_name:app.fonts.heading
                    size_hint_y :None
                    height:dp(42)

                AnchorLayout:
                    orientation :'vertical'
                    spacing: dp(8)
                    anchor_y: 'top'

                    Label:
                        id : instructions
                        text: 'Meat is valued as a complete protein food containing all the amino acids necessary for the human body. The fat of meat, which varies widely with the species, quality, and cut, is a valuable source of energy and also influences the flavour, juiciness, and tenderness of the lean. Parts such as livers, kidneys, hearts, and other portions are excellent sources of vitamins and of essential minerals, easily assimilated by the human system.'
                        valign:'top'
                        size:self.texture_size
                        size_hint_y:None
                        text_size: [self.width, None]
                        font_name :app.fonts.body
                        font_size:app.fonts.size.h6
                        color:app.colors.primary
                RoundedButton:
                    text: 'Change Schedule'
                    font_name : app.fonts.subheading
                    color: app.colors.white
                    bcolor: app.colors.warning
                    radius: [self.height*0.3]
                    size_hint_y: None
                    height: dp(54)
        BoxLayout:
            orientation : 'vertical'
            AnchorLayout:
                anchor_x:'right'
                size_hint_y: 0.55
                Widget:
                    canvas.before:
                        Color:
                            rgba: [1,1,1,1]
                        RoundedRectangle:
                            pos:[self.pos[0]+(self.size[0]-(self.size[0]*0.7)), self.pos[1]]
                            size:[self.size[0]+dp(24), self.size[1]]
                            source:root.source
                Widget:
                    size_hint_y:0.45

<SmoothToggle@ToggleButton>:
    color : app.colors.warning if self.state == 'down ' else [0,0,0,1]
    background_normal:''
    background_down:''
    background_color:[0,0,0,0]
    group:'tabs'
    font_name: app.fonts.subheading
    canvas.before:
        Color:
            rgba: app.colors.warning if self.state == 'down' else [0,0,0,0]
        Ellipse:
            pos:[self.pos[0]+(self.size[0]*0.5), self.pos[1]]
            size:[dp(4),dp(4)]

















